### ISSUE TITLE
Cannot plant saplings on permafrost

### ISSUE THREAD

**Issue by medsal15** [Delocuro/Minestrapp-1.12#1]

**Comment by werty1124** [comment]
Should be an easy fix

**Comment by Delocuro** [comment]
Good catch - yeah, that'll be fixed for the next update.

**Comment by werty1124** [comment]
@Delocuro you should add me to this repo so I can help out, and what are you guys using to communicate now?

**Comment by Delocuro** [comment]
@werty1124 Finally tracked down the add contributor button, so you should be good to go! We're still using Skype, but we should probably have switched over to Discord or something like a long time ago, lmao

**Comment by werty1124** [comment]
@Delocuro I don't even have Skype anymore, but i do have discord

**Comment by werty1124** [comment]
This is fixed for my next commit but I don't seem to be able to close issues. We should probably migrate this to the Minestrappolation team group
