### ISSUE TITLE
[1.12.2] Recipes don't use Oredictionaries

### ISSUE THREAD

**Issue by MasterEnderman** [Delocuro/Minestrapp-1.12#11]
For example the copper tools. The copper ingot has the Oredictionary ingotCopper but the tools only accept the copper from minestrapp. The recipes should use the Oredictionary instead of the item so you can make the tools with all copper ingots.

**Comment by Delocuro** [comment]
Good catch - when I started coding M5, I ended up adding OreDict support about midway through the first release, so half of the recipes have proper OreDict support, while the other half if missing it entirely. I'll try and get the Tool & Weapon recipes fixed for 5.2.1, but let me know if you run into any other recipes that need OreDict support - there's probably more that I've missed, but I haven't had the time to go through every json file and check yet.
