### ISSUE TITLE
Glacial Invincium is not so invincible

### ISSUE THREAD

**Issue by ghost** [Delocuro/Minestrapp-1.12#12]
Mod version: 5.2.1
Minecraft Version: 1.12.2
Forge Build: 2611

Glacial Invincium might not be minable, but TNT works just fine. Also worth noting that the deposit which sits atop the mounds also has 0 blast resistance.

**Comment by Delocuro** [comment]
lol whoops, good catch - totally forgot to set the blast resistance on those. That'll be fixed for the next version.
