### ISSUE TITLE
Silverfish Eggs in biome stone colours

### ISSUE THREAD

**Issue by ghost** [Delocuro/Minestrapp-1.12#16]
It'd be good if the silverfish eggs could be swapped out for the relevant stone colour when they're in a biome with non-vanilla stone. Currently they're far too easy to spot and avoid.

**Comment by Delocuro** [comment]
That's been planned for a while, I just keep forgetting to do it, lol. Thanks for making an issue for it though - maybe that'll be enough for me to remember to actually finish that for 5.3.0. :P
