### ISSUE TITLE
Hopper recipe override: can't undo

### ISSUE THREAD

**Issue by ghost** [Delocuro/Minestrapp-1.12#17]
Details of MC version and all that are the same as my previous bug reports.

If I try to reinstate the vanilla hopper recipe with CraftTweaker, any new recipe I add for it doesn't appear to work. I assume this is because the vanilla recipe is removed by Minestrapp after CT does any scripted recipe changes. Could all recipe removals done by Minestrapp please happen before CT does its thing?

**Comment by Delocuro** [comment]
I'll have to look into it, but in theory it should be an easy fix - I'm guessing it's just a matter of moving the recipe removals from init to preInit. If it's an easy fix I'll have that done for 5.3.0.

**Comment by Delocuro** [comment]
Decided making this a config option would make more sense -- currently there's only one option that stops the removal of all Vanilla recipes, but I'll add per-recipe options in a future update.
