### ISSUE TITLE
Berry Bushes are HELLA Fucked on Multiplayer

### ISSUE THREAD

**Issue by Delocuro** [Delocuro/Minestrapp-1.12#24]
Something's super messed up with Berry Bushes' harvesting code -- harvesting Strawberry & Blueberry Bushes works fine, but I somehow managed to get 4 stacks of Blackberries from 1 bush. Drops also don't seem to sync to the proper spaces in the inventory client-side, as they shuffled around upon re-logging.

EDIT: Upon further inspection only Blackberries seem to have the quantity issue -- dunno why though, I think they're set up the same way as the others. I may push a hotfix for this one, since that's pretty impressively gamebreaking, lmao

**Comment by werty1124** [comment]
I can't seem to reproduce this bug

**Comment by werty1124** [comment]
should be fixed if not just reopen this
