### ISSUE TITLE
JEIplugin

### ISSUE THREAD

**Issue by werty1124** [Delocuro/Minestrapp-1.12#3]
Working on the JEI plugin just leave whatever needs supported here.
- [ ] Alloy Furnace
- [ ] Crusher (Will probably need flags for things obtained via the bonus output slot as well)

**Comment by SmallSansSerif** [comment]
Any progress on this?

**Comment by werty1124** [comment]
@SmallSansSerif Yep, it should be ready for the next update

**Comment by SmallSansSerif** [comment]
@werty1124 Any updates?

**Comment by LordEpos** [comment]
I also would like updates on these updates.

**Comment by werty1124** [comment]
It's being worked on again.

**Comment by werty1124** [comment]
@LordEpos @SmallSansSerif This has been completed and will be in the next update sorry it took so long
