### ISSUE TITLE
missing tanning solvent recipe

### ISSUE THREAD

**Issue by VanillaVanity7** [Delocuro/Minestrapp-1.12#32]
there seems to be no way to get tanning solvent in survival. JEI says the recipe doesn't even exist. I tried foregoing the solvent & trying to make tanner with just water, but that's not possible either.

**Comment by Delocuro** [comment]
Try this and see if it works:

WWW
RMB
WWW

where W = Water Bottle, R = Red Mushroom, B = Brown Mushroom, and M = Moss. There's a JEI bug where it displays Water Bottles as "Uncraftable Potion"s, but you should be able to craft them still.

**Comment by Delocuro** [comment]
This should be resolved regardless in 5.7.0 -- I went ahead and changed the solvent recipe to Glass Bottles instead of Water Bottles to reduce confusion.
