### ISSUE TITLE
Compat with Railcraft

### ISSUE THREAD

**Issue by ZigTheHedge** [Delocuro/Minestrapp-1.12#34]
Hello again, my friend :)
Here's another crush caused by incompatibility with Railcraft (12.0.0).
https://pastebin.com/YdkKKsAb

Steps to reproduce:
1. Install Railcraft 12.0.0
2. Take any skull from creative
3. Select it in hotbar
4. Enjoy ;)

**Comment by Delocuro** [comment]
Yeah, we’ve run into that with some item physics mods as well — it’s really more of a bug with rail raft than it is with Minestrapp, though. I don’t know what exactly railcraft does to their hoverstates, but they apparently neglected to add a check to see if any given block actually has all 6 facing states. I’d recommend bringing this up with their devs.
