### ISSUE TITLE
Crash with skull, mods (minestrap v.5.6.5, railcraft v.12.0.0, foamfix v.0.10.5) minecraft v.1.12.2

### ISSUE THREAD

**Issue by Dragonborn777** [Delocuro/Minestrapp-1.12#35]
HELP MEEEEEEEEEEEEEEEEEEEEEEEEE!!!
Crash or link on crash:
Link - https://paste.dimdev.org/xipaguseri.mccrash
Crash - 
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 2019-04-29 12:29:02 MSK
Description: Ticking memory connection

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block minestrapp:skull_bat, it is not an allowed value
    at pl.asie.foamfix.common.FoamyBlockState.withProperty(FoamyBlockState.java:59)
    at minestrapp.block.BlockMSkull.getStateFromMeta(BlockMSkull.java:170)
    at mods.railcraft.common.util.inventory.InvTools.getBlockStateFromStack(InvTools.java:488)
    at mods.railcraft.common.blocks.tracks.TrackTools.isRailBlock(TrackTools.java:73)
    at mods.railcraft.common.advancements.criterion.TrackItemPredicate.test(TrackItemPredicate.java:66)
    at net.minecraft.advancements.critereon.InventoryChangeTrigger$Instance.test(SourceFile:104)
    at net.minecraft.advancements.critereon.InventoryChangeTrigger$Listeners.trigger(SourceFile:149)
    at net.minecraft.advancements.critereon.InventoryChangeTrigger.trigger(SourceFile:69)
    at net.minecraft.entity.player.EntityPlayerMP.sendSlotContents(EntityPlayerMP.java:972)
    at net.minecraft.inventory.Container.detectAndSendChanges(Container.java:91)
    at net.minecraft.inventory.Container.addListener(Container.java:53)
    at net.minecraft.entity.player.EntityPlayerMP.addSelfToInternalCraftingInventory(EntityPlayerMP.java:289)
    at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:256)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Ticking connection --
  Connection: net.minecraft.network.NetworkManager@29a7849f

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1444631192 bytes (1377 MB) / 4328521728 bytes (4128 MB) up to 10737418240 bytes (10240 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 15, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2824 Optifine OptiFine_1.12.2_HD_U_E4_pre1 99 mods loaded, 99 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                   | Version                  | Source                                             | Signature                                |
       |:------ |:------------------------------------ |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                            | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                                  | 9.42                     | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                                  | 8.0.99.99                | forge-1.12.2-14.23.5.2824.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                                | 14.23.5.2824             | forge-1.12.2-14.23.5.2824.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | smoothfontcore                       | mc1.12.2-1.16            | minecraft.jar                                      | None                                     |
       | LCHIJA | foamfixcore                          | 7.7.4                    | minecraft.jar                                      | None                                     |
       | LCHIJA | smoothfont                           | mc1.12.2-1.16.2          | SmoothFont-mc1.12.2-1.16.2.jar                     | None                                     |
       | LCHIJA | aoa3                                 | 3.0.2                    | AoA3-3.0.2.jar                                     | None                                     |
       | LCHIJA | applecore                            | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                       | None                                     |
       | LCHIJA | baubles                              | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
       | LCHIJA | atum                                 | 2.0.2                    | Atum-1.12.2-2.0.2.jar                              | None                                     |
       | LCHIJA | patchouli                            | 1.0-18                   | Patchouli-1.0-18.jar                               | None                                     |
       | LCHIJA | naturesaura                          | r15                      | NaturesAura-r15.jar                                | None                                     |
       | LCHIJA | auraddons                            | 1.7.2                    | Auraddons-1.7.2-NAr14.jar                          | None                                     |
       | LCHIJA | crafttweaker                         | 4.1.17                   | CraftTweaker2-1.12-4.1.17.jar                      | None                                     |
       | LCHIJA | mtlib                                | 3.0.6                    | MTLib-3.0.6.jar                                    | None                                     |
       | LCHIJA | modtweaker                           | 4.0.17                   | modtweaker-4.0.17.jar                              | None                                     |
       | LCHIJA | jei                                  | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                          | None                                     |
       | LCHIJA | quark                                | r1.5-146                 | Quark-r1.5-146.jar                                 | None                                     |
       | LCHIJA | autoreglib                           | 1.3-26                   | AutoRegLib-1.3-26.jar                              | None                                     |
       | LCHIJA | ichunutil                            | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                         | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | backtools                            | 7.0.0                    | BackTools-1.12.2-7.0.0.jar                         | None                                     |
       | LCHIJA | bibliocraft                          | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | LCHIJA | blockdrops                           | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                        | None                                     |
       | LCHIJA | bonsaitrees                          | 1.1.2                    | bonsaitrees-1.1.2-b144.jar                         | None                                     |
       | LCHIJA | champions                            | 1.12.2-1.0.8             | champions-1.12.2-1.0.8.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | codechickenlib                       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | extendedrenderer                     | v1.0                     | coroutil-1.12.1-1.2.31.jar                         | None                                     |
       | LCHIJA | coroutil                             | 1.12.1-1.2.31            | coroutil-1.12.1-1.2.31.jar                         | None                                     |
       | LCHIJA | configmod                            | v1.0                     | coroutil-1.12.1-1.2.31.jar                         | None                                     |
       | LCHIJA | cosmeticarmorreworked                | 1.12.2-v4                | CosmeticArmorReworked-1.12.2-v4.jar                | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | tombmanygraves                       | 1.12-4.2.0               | TombManyGraves-1.12-4.2.0.jar                      | None                                     |
       | LCHIJA | cosmeticarmorreworked|tombmanygraves | 1.12.2-v4                | CosmeticArmorReworked-1.12.2-v4.jar                | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | craftingtweaks                       | 8.1.9                    | CraftingTweaks_1.12.2-8.1.9.jar                    | None                                     |
       | LCHIJA | ctgui                                | 1.0.0                    | CraftTweaker2-1.12-4.1.17.jar                      | None                                     |
       | LCHIJA | crafttweakerjei                      | 2.0.3                    | CraftTweaker2-1.12-4.1.17.jar                      | None                                     |
       | LCHIJA | custommainmenusound                  | 1.0                      | custom_main_menu_sound-1.12.2.jar                  | None                                     |
       | LCHIJA | customloadingscreen                  | 1.12.2-1.4.0.3           | CustomLoadingScreen-1.12.2-1.4.0.3.jar             | None                                     |
       | LCHIJA | custommainmenu                       | 2.0.9                    | CustomMainMenu-MC1.12.2-2.0.9.jar                  | None                                     |
       | LCHIJA | ding                                 | 1.0.1                    | Ding-1.12.1-1.0.1.jar                              | None                                     |
       | LCHIJA | doggytalents                         | 1.14.2.396               | DoggyTalents-1.12.2-1.14.2.396-universal.jar       | None                                     |
       | LCHIJA | dummycore                            | 2.4.112.5.               | DummyCoreUnofficial-2.4.112.5.jar                  | None                                     |
       | LCHIJA | eleccore                             | 1.9.452                  | ElecCore-1.12.2-1.9.452.jar                        | None                                     |
       | LCHIJA | erebus                               | 1.0.29                   | Erebus-1.0.29.jar                                  | None                                     |
       | LCHIJA | essentialcraft                       | 4.9.112.5                | EssentialCraftUnofficial-4.9.112.5.jar             | None                                     |
       | LCHIJA | extrautils2                          | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | LCHIJA | foamfix                              | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                          | None                                     |
       | LCHIJA | forbidden_arcanus                    | 1.12.2-0.6               | forbidden_arcanus-1.12.2-0.6.jar                   | None                                     |
       | LCHIJA | ftblib                               | 5.4.1.93                 | FTBLib-5.4.1.93.jar                                | None                                     |
       | LCHIJA | ftbutilities                         | 5.4.0.90                 | FTBUtilities-5.4.0.90.jar                          | None                                     |
       | LCHIJA | glacidus                             | 1.2.1                    | Glacidus-1.12.2-v1.2.1.jar                         | None                                     |
       | LCHIJA | gokistats                            | @version@                | gokiStats-1.2.5.1.jar                              | None                                     |
       | LCHIJA | hats                                 | 7.0.0                    | Hats-1.12.2-7.0.2.jar                              | None                                     |
       | LCHIJA | waila                                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCHIJA | ignitehud                            | 1.12-b0.1.1              | ignitehud_1.12-b0.1.1.jar                          | None                                     |
       | LCHIJA | improvedbackpacks                    | 1.12.2-1.4.0.0           | ImprovedBackpacks-1.12.2-1.4.0.0.jar               | None                                     |
       | LCHIJA | inventorytweaks                      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | journeymap                           | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                        | None                                     |
       | LCHIJA | keywizard                            | 1.12.2-1.5.5             | keywizard-1.12.2-1.5.5.jar                         | None                                     |
       | LCHIJA | lolotweaks                           | 1.0.1                    | lolotweaks-1.0.1.jar                               | None                                     |
       | LCHIJA | malisiscore                          | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                       | None                                     |
       | LCHIJA | malisisdoors                         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
       | LCHIJA | malisisswitches                      | 1.12.2-5.1.0             | malisisswitches-1.12.2-5.1.0.jar                   | None                                     |
       | LCHIJA | metalchests                          | v4.0.1.g01955d6          | MetalChests-v4.0.1.g01955d6.jar                    | None                                     |
       | LCHIJA | millenaire                           | Millénaire 7.2.0         | millenaire-1.12.2-7.2.0.jar                        | None                                     |
       | LCHIJA | minestrapp                           | 5.4.0A                   | Minestrappolation+5.6.5.jar                        | None                                     |
       | LCHIJA | mobends                              | 0.24                     | mobends-0.24_for_MC-1.12.jar                       | None                                     |
       | LCHIJA | mousetweaks                          | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
       | LCHIJA | multimob                             | 1.0.5                    | multimob-1.0.5.jar                                 | None                                     |
       | LCHIJA | naturescompass                       | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                    | None                                     |
       | LCHIJA | numina                               | 1.12.2-1.0.36            | Numina-1.12.2-1.0.36.jar                           | None                                     |
       | LCHIJA | omlib                                | 3.0.1-162                | omlib-1.12.2-3.0.1-162.jar                         | None                                     |
       | LCHIJA | ompd                                 | 3.0.0-36                 | ompd-1.12.2-3.0.0-36.jar                           | None                                     |
       | LCHIJA | openmodularturrets                   | 3.0.1-264                | openmodularturrets-1.12.2-3.0.1-264.jar            | None                                     |
       | LCHIJA | p455w0rdslib                         | 2.0.36                   | p455w0rdslib-1.12.2-2.0.36.jar                     | None                                     |
       | LCHIJA | primitivemobs                        | 1.2.3a                   | primitivemobs-1.2.3a.jar                           | None                                     |
       | LCHIJA | railcraft                            | 12.0.0                   | railcraft-12.0.0.jar                               | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | reborncore                           | 3.13.9.433               | RebornCore-1.12.2-3.13.9.433-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | resourceloader                       | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | additionalstructures                 | 2.2.2                    | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar   | None                                     |
       | LCHIJA | rootsclassic                         | 1.12.2-1.1.5             | RootsClassic-1.12.2-1.1.5.jar                      | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
       | LCHIJA | scarper                              | 1.1                      | scarper-1.1.jar                                    | None                                     |
       | LCHIJA | sgcraft                              | 1.13.2                   | SGCraft-1.20.3.jar                                 | None                                     |
       | LCHIJA | specialai                            | 1.1.0_for_mc1.12.2       | specialai-1.1.0_for_mc1.12.2.jar                   | None                                     |
       | LCHIJA | specialmobs                          | 1.0.2_for_mc1.12.2       | specialmobs-1.0.2_for_mc1.12.2.jar                 | None                                     |
       | LCHIJA | spiceoflife                          | 1.3.12                   | SpiceOfLife-mc1.12-1.3.12.jar                      | None                                     |
       | LCHIJA | stevescarts                          | 2.4.29.132               | StevesCarts-1.12.2-2.4.29.132.jar                  | None                                     |
       | LCHIJA | theoneprobe                          | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                        | None                                     |
       | LCHIJA | toughasnails                         | 3.1.0.139                | ToughAsNails-1.12.2-3.1.0.139-universal.jar        | None                                     |
       | LCHIJA | vanillafix                           | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                           | None                                     |
       | LCHIJA | weather2                             | 1.12.1-2.6.12            | weather2-1.12.1-2.6.12.jar                         | None                                     |
       | LCHIJA | xtones                               | 1.12-1.0.8-11            | Xtones-1.12-1.0.8-11.jar                           | None                                     |
       | LCHIJA | arcaneworld                          | 0.0.9                    | arcaneworld-1.12.2-0.0.9.jar                       | None                                     |
       | LCHIJA | lemonlib                             | 1.3.0                    | lemonlib-1.12.2-1.3.0.jar                          | None                                     |
       | LCHIJA | structurize                          | 1.12.2-0.10.63-ALPHA     | structurize-1.12.2-0.10.63-ALPHA.jar               | None                                     |
       | LCHIJA | minecolonies                         | 1.12.2-0.10.202-RELEASE  | minecolonies-1.12.2-0.10.202-RELEASE-universal.jar | None                                     |
       | LCHIJA | phosphor-lighting                    | 1.12.2-0.2.0             | phosphor-1.12.2-0.2.0+build37-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | simpleundergroundbiomes              | 1.0.0                    | simpleundergroundbiomes-1.0.0.jar                  | None                                     |
       | LCHIJA | eleccoreloader                       | 1.9.452                  | ElecCore-1.12.2-1.9.452.jar                        | None                                     |
  Loaded coremods (and transformers): MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      LoadingPlugin (Quark-r1.5-146.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ClsPlugin (CustomLoadingScreen-1.12.2-1.4.0.3.jar)
                                        alexiil.mc.mod.load.coremod.ClsTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-1.16.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      DCLoadingPlugin (DummyCoreUnofficial-2.4.112.5.jar)
                                        DummyCore.ASM.DCASMManager
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.0+build37-universal.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  [DummyCore]: 'Special case ASM modification mods: ''Note, that these mods might not be involved in the crash in ANY WAY!''DummyCore just prints some known mods for a lot of ASM modifications''dummycore''CodeChickenLib'
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.13.9.433
              Runtime Debofucsation 1
              RenderEngine: 1
  Suspected Mods: FoamFix (foamfix), Minestrappolation 5 (minestrapp), Railcraft (railcraft)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Dragonborn_'/588, l='Новый мир---------', x=189.84, y=67.93, z=264.98]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Client Crashes Since Restart: 0
  Integrated Server Crashes Since Restart: 2

**Comment by MisticaX** [comment]
Hello! I have the same problem with sculls, exactly when the scull on the hot bar. Game crashed and impossible to load the world again (thanks i have aroma). Also it is happened with machines. The crasher machine crashed the game when i tried to connect pipes (that game was lost forever therefore no logs saved)  
Mostly all mods up to date and sims like no conflicts. 
[mods.txt](https://github.com/MinestrapTeam/Minestrapp-1.12/files/3722536/mods.txt)
[crash-2019-10-13_23.54.23-server.txt](https://github.com/MinestrapTeam/Minestrapp-1.12/files/3722531/crash-2019-10-13_23.54.23-server.txt)
[latest.log](https://github.com/MinestrapTeam/Minestrapp-1.12/files/3722532/latest.log)
debug file more than 25mb can't load...

**Comment by Delocuro** [comment]
Sorry, haven't been good about checking up on GitHub lately.

Anyway, unfortunately I don't think there's anything I can really do about this one. The issue seems to be with FoamFix -- apparently it doesn't handle any block without all 6 directional states well. It's been reported with other directional blocks like Alloy Furnaces and Tanning Racks as well, but none of these blocks have any issues without FoamFix installed, so it's definitely not a Minestrapp problem. I'd suggest uninstalling FoamFix and seeing if that works -- doesn't look like it's a required library for anything, it just appears to be a performance optimization mod.
