### ISSUE TITLE
Alloy Furnaces are apparently horribly broken and I don't know how to fix them.

### ISSUE THREAD

**Issue by Delocuro** [Delocuro/Minestrapp-1.12#5]
Just found out this was an issue after the release yesterday - apparently Alloy Furnaces currently only consume 1 item from each slot no matter how many items the recipe is supposed to require, and at the moment it also only functions if you put in exactly as many items as the recipe wants.

I know how to fix the latter - it was just a matter of replacing an == with a >=. But I can't figure out for the life of me how to get the quantity of the itemstack being smelted and subtract that many from the Alloy Furnace. Arrays are confusing as shit, and I'm bad at code, but this reeeeeally needs to get fixed fast - like within the next day or two - since it makes the Alloy Furnace simultaneously frustrating to use and ludicrously overpowered in survival.

**Comment by triplg3** [comment]
I did it
